// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Banner 1 variation for Banners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Banners*
 */
type BannersSliceVariation = BannersSliceDefault;

/**
 * Banners Shared Slice
 *
 * - **API ID**: `banners`
 * - **Description**: Banners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannersSlice = prismic.SharedSlice<
  "banners",
  BannersSliceVariation
>;

/**
 * Primary content in *Categories → Categories → Primary*
 */
export interface CategoriesSliceDefaultPrimary {
  /**
   * Title field in *Categories → Categories → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the category slice
   * - **API ID Path**: categories.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Categories variation for Categories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Categories*
 */
type CategoriesSliceVariation = CategoriesSliceDefault;

/**
 * Categories Shared Slice
 *
 * - **API ID**: `categories`
 * - **Description**: Categories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoriesSlice = prismic.SharedSlice<
  "categories",
  CategoriesSliceVariation
>;

/**
 * Product collection variation for Collections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Collections*
 */
type CollectionsSliceVariation = CollectionsSliceDefault;

/**
 * Collections Shared Slice
 *
 * - **API ID**: `collections`
 * - **Description**: Collections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollectionsSlice = prismic.SharedSlice<
  "collections",
  CollectionsSliceVariation
>;

/**
 * Primary content in *Deals → Shocking deals → Primary*
 */
export interface DealsSliceDefaultPrimary {
  /**
   * Title field in *Deals → Shocking deals → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title on top of the deal section
   * - **API ID Path**: deals.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Image field in *Deals → Shocking deals → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deals.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Shocking deals variation for Deals Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DealsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DealsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Deals*
 */
type DealsSliceVariation = DealsSliceDefault;

/**
 * Deals Shared Slice
 *
 * - **API ID**: `deals`
 * - **Description**: Deals
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DealsSlice = prismic.SharedSlice<"deals", DealsSliceVariation>;

/**
 * Upcoming event variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>;

/**
 * Item in *Example → Default → Primary → Carousel*
 */
export interface ExampleSliceDefaultPrimaryCarouselItem {}

/**
 * Primary content in *Example → Default → Primary*
 */
export interface ExampleSliceDefaultPrimary {
  /**
   * Title field in *Example → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Carousel field in *Example → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<ExampleSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for Example Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExampleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Example*
 */
type ExampleSliceVariation = ExampleSliceDefault;

/**
 * Example Shared Slice
 *
 * - **API ID**: `example`
 * - **Description**: Example
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSlice = prismic.SharedSlice<
  "example",
  ExampleSliceVariation
>;

/**
 * Primary content in *Forms → Equipment Set → Primary*
 */
export interface FormsSliceDefaultPrimary {
  /**
   * Title field in *Forms → Equipment Set → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the form
   * - **API ID Path**: forms.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Short description field in *Forms → Equipment Set → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description of the form section
   * - **API ID Path**: forms.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;

  /**
   * Background Image field in *Forms → Equipment Set → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: forms.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Equipment Set variation for Forms Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Forms*
 */
type FormsSliceVariation = FormsSliceDefault;

/**
 * Forms Shared Slice
 *
 * - **API ID**: `forms`
 * - **Description**: Forms
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormsSlice = prismic.SharedSlice<"forms", FormsSliceVariation>;

/**
 * Item in *GridSections → Grid section 1 → Primary → Images*
 */
export interface GridSectionsSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *GridSections → Grid section 1 → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *GridSections → Grid section 2 → Primary → Images*
 */
export interface GridSectionsSliceGridSection2PrimaryImagesItem {
  /**
   * Image field in *GridSections → Grid section 2 → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.gridSection2.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *GridSections → Grid section 3 → Primary → Images*
 */
export interface GridSectionsSliceGridSection3PrimaryImagesItem {
  /**
   * Image field in *GridSections → Grid section 3 → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.gridSection3.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GridSections → Grid section 1 → Primary*
 */
export interface GridSectionsSliceDefaultPrimary {
  /**
   * Images field in *GridSections → Grid section 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<GridSectionsSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Grid section 1 variation for GridSections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSectionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridSectionsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *GridSections → Grid section 2 → Primary*
 */
export interface GridSectionsSliceGridSection2Primary {
  /**
   * Images field in *GridSections → Grid section 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.gridSection2.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<GridSectionsSliceGridSection2PrimaryImagesItem>
  >;
}

/**
 * Grid section 2 variation for GridSections Slice
 *
 * - **API ID**: `gridSection2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSectionsSliceGridSection2 = prismic.SharedSliceVariation<
  "gridSection2",
  Simplify<GridSectionsSliceGridSection2Primary>,
  never
>;

/**
 * Primary content in *GridSections → Grid section 3 → Primary*
 */
export interface GridSectionsSliceGridSection3Primary {
  /**
   * Images field in *GridSections → Grid section 3 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_sections.gridSection3.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<GridSectionsSliceGridSection3PrimaryImagesItem>
  >;
}

/**
 * Grid section 3 variation for GridSections Slice
 *
 * - **API ID**: `gridSection3`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSectionsSliceGridSection3 = prismic.SharedSliceVariation<
  "gridSection3",
  Simplify<GridSectionsSliceGridSection3Primary>,
  never
>;

/**
 * Slice variation for *GridSections*
 */
type GridSectionsSliceVariation =
  | GridSectionsSliceDefault
  | GridSectionsSliceGridSection2
  | GridSectionsSliceGridSection3;

/**
 * GridSections Shared Slice
 *
 * - **API ID**: `grid_sections`
 * - **Description**: GridSections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSectionsSlice = prismic.SharedSlice<
  "grid_sections",
  GridSectionsSliceVariation
>;

/**
 * Featured live variation for Livestreams Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LivestreamsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Livestreams*
 */
type LivestreamsSliceVariation = LivestreamsSliceDefault;

/**
 * Livestreams Shared Slice
 *
 * - **API ID**: `livestreams`
 * - **Description**: Livestreams
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LivestreamsSlice = prismic.SharedSlice<
  "livestreams",
  LivestreamsSliceVariation
>;

/**
 * Membership variation for Memberships Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembershipsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Memberships*
 */
type MembershipsSliceVariation = MembershipsSliceDefault;

/**
 * Memberships Shared Slice
 *
 * - **API ID**: `memberships`
 * - **Description**: Memberships
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembershipsSlice = prismic.SharedSlice<
  "memberships",
  MembershipsSliceVariation
>;

/**
 * Grid news variation for News Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *News*
 */
type NewsSliceVariation = NewsSliceDefault;

/**
 * News Shared Slice
 *
 * - **API ID**: `news`
 * - **Description**: News
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSlice = prismic.SharedSlice<"news", NewsSliceVariation>;

/**
 * Special offer variation for Offers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Offers*
 */
type OffersSliceVariation = OffersSliceDefault;

/**
 * Offers Shared Slice
 *
 * - **API ID**: `offers`
 * - **Description**: Offers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffersSlice = prismic.SharedSlice<"offers", OffersSliceVariation>;

/**
 * New products variation for Products Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Best seller products variation for Products Slice
 *
 * - **API ID**: `bestSellerProducts`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceBestSellerProducts = prismic.SharedSliceVariation<
  "bestSellerProducts",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Products*
 */
type ProductsSliceVariation =
  | ProductsSliceDefault
  | ProductsSliceBestSellerProducts;

/**
 * Products Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<
  "products",
  ProductsSliceVariation
>;

/**
 * Primary content in *Promotions → Promotion banners → Primary*
 */
export interface PromotionsSliceDefaultPrimary {
  /**
   * Title field in *Promotions → Promotion banners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the promotion section
   * - **API ID Path**: promotions.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Short description field in *Promotions → Promotion banners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description of the promotion section
   * - **API ID Path**: promotions.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;

  /**
   * Background Image field in *Promotions → Promotion banners → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotions.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Promotion banners variation for Promotions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PromotionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Promotions*
 */
type PromotionsSliceVariation = PromotionsSliceDefault;

/**
 * Promotions Shared Slice
 *
 * - **API ID**: `promotions`
 * - **Description**: Promotions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionsSlice = prismic.SharedSlice<
  "promotions",
  PromotionsSliceVariation
>;

/**
 * Banner and product suggestion variation for Suggestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuggestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Suggestions*
 */
type SuggestionsSliceVariation = SuggestionsSliceDefault;

/**
 * Suggestions Shared Slice
 *
 * - **API ID**: `suggestions`
 * - **Description**: Suggestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuggestionsSlice = prismic.SharedSlice<
  "suggestions",
  SuggestionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.WriteClientConfig,
    ): prismic.WriteClient;
  }

  interface CreateMigration {
    (): prismic.Migration;
  }

  namespace Content {
    export type {
      BannersSlice,
      BannersSliceVariation,
      BannersSliceDefault,
      CategoriesSlice,
      CategoriesSliceDefaultPrimary,
      CategoriesSliceVariation,
      CategoriesSliceDefault,
      CollectionsSlice,
      CollectionsSliceVariation,
      CollectionsSliceDefault,
      DealsSlice,
      DealsSliceDefaultPrimary,
      DealsSliceVariation,
      DealsSliceDefault,
      EventsSlice,
      EventsSliceVariation,
      EventsSliceDefault,
      ExampleSlice,
      ExampleSliceDefaultPrimaryCarouselItem,
      ExampleSliceDefaultPrimary,
      ExampleSliceVariation,
      ExampleSliceDefault,
      FormsSlice,
      FormsSliceDefaultPrimary,
      FormsSliceVariation,
      FormsSliceDefault,
      GridSectionsSlice,
      GridSectionsSliceDefaultPrimaryImagesItem,
      GridSectionsSliceDefaultPrimary,
      GridSectionsSliceGridSection2PrimaryImagesItem,
      GridSectionsSliceGridSection2Primary,
      GridSectionsSliceGridSection3PrimaryImagesItem,
      GridSectionsSliceGridSection3Primary,
      GridSectionsSliceVariation,
      GridSectionsSliceDefault,
      GridSectionsSliceGridSection2,
      GridSectionsSliceGridSection3,
      LivestreamsSlice,
      LivestreamsSliceVariation,
      LivestreamsSliceDefault,
      MembershipsSlice,
      MembershipsSliceVariation,
      MembershipsSliceDefault,
      NewsSlice,
      NewsSliceVariation,
      NewsSliceDefault,
      OffersSlice,
      OffersSliceVariation,
      OffersSliceDefault,
      ProductsSlice,
      ProductsSliceVariation,
      ProductsSliceDefault,
      ProductsSliceBestSellerProducts,
      PromotionsSlice,
      PromotionsSliceDefaultPrimary,
      PromotionsSliceVariation,
      PromotionsSliceDefault,
      SuggestionsSlice,
      SuggestionsSliceVariation,
      SuggestionsSliceDefault,
    };
  }
}
