export {default as subcription} from "./subcription_lv1.svg";
export {default as vector} from "./vector.svg";
export {default as coin} from "./coin.svg";
export {default as bg_coin} from "./bg-coin.svg";
export {default as badge_logo} from "./logo-badge.svg";
export {default as logo_star} from "./logo_star.svg";
export {default as bell} from "./bell.svg";
export {default as Batminton} from "./batminton.svg";
export {default as Pickleball} from "./pickleball.svg";
export {default as Tennis} from "./tennis.svg";
export {default as Shoes} from "./shoes.svg";
export {default as Football} from "./football.svg";
export {default as Basketball} from "./basketball.svg";
export {default as Livestream} from "./livestream.svg";
export {default as News} from "./news.svg";
export {default as Brand} from "./brand.svg";
export {default as TrendingSearch} from "./trending_search.svg";
export {default as Telegram} from "./telegram.svg";
export {default as Zalo} from "./zalo.svg";
export {default as TickSuccess} from "./tick.svg";
export {default as CouponTag} from "./tag-coupon.svg";
export {default as Location} from "./location.svg";
export {default as Map} from "./map.svg";
export {default as Momo} from "./momo.svg";
export {default as CreditCardIco} from "./credit-card.svg";
export {default as Appota} from "./appota.svg";
export {default as NvbPlay} from "./nvb-wallet.svg";
export {default as VnPay} from "./vnpay.svg";
export {default as Cod} from "./cod.svg";
export {default as WaitExec} from "./wait-execute.svg";
export {default as WaitPayment} from "./wait-payment.svg";
export {default as Delivered} from "./delivered.svg";
export {default as Delivering} from "./delivering.svg";
export {default as Cancel} from "./cancel.svg";
export {default as CancelRequest} from "./cancel-request.svg";
export {default as RollbackRequest} from "./rollback-request.svg";
export {default as PaymentReturn} from "./payment-return.svg";
export {default as OrderError} from "./order-error.svg";
export {default as OrderSuccess} from "./order-success.svg";
export {default as OrderWarning} from "./order-warning.svg";
export {default as FireWork} from "./fire-work.svg";
export {default as Stripe} from "./stripe.svg";
export {default as MasterCard} from "./master-card.svg";
export {default as JCB} from "./jcb.svg";
export {default as Visa} from "./visa.svg";
export {default as CreditCardPlus} from "./credit-card-plus.svg";
export {default as Bitcoin} from "./bitcoin.svg";
export {default as Tether} from "./tether-us.svg";
export {default as Tether2} from "./tether-us2.svg";
export {default as Doge} from "./doge.svg";
export {default as Solana} from "./sonala.svg";
export {default as Ethereum} from "./ethereum.svg";
export {default as Copy} from "./copy-icon.svg";
export {default as Techcombank} from "./techcombank.svg";
export {default as Pvcombank} from "./pvcombank.svg";
export {default as Mbbank} from "./mb-bank.svg";
export {default as Subcription} from "./subcription-bg.svg";
export {default as NVBPlay_Subcription} from "./nvbplay_subcription.svg";
export {default as FreeShipping} from "./freeship.svg";
export {default as Gift} from "./gift.svg";
export {default as Minigame} from "./minigame.svg";
export {default as Voucher} from "./sale.svg";
export {default as Crown} from "./newproduct.svg";
export {default as BgMobileSubcription} from "./bg-subcription-mobile.svg";
export {default as AppSubcription} from "./app-subcription.svg";
export {default as Cart} from "./cart.svg";
export {default as ForPayment} from "./for-payment.svg";
export {default as Play} from "./play.svg";
export {default as X} from "./x.svg";
export {default as Info} from "./info-filled.svg";
export {default as Error} from "./x-filled.svg";
export {default as Warning} from "./warning-filled.svg";
export {default as Success} from "./check-filled.svg";
export {default as Pattern} from "./pattern.svg";
export {default as Shirt} from "./shirt.svg";
export {default as Collection} from "./collection.svg";
export {default as StoreSuggest} from "./store-suggest.svg";
export {default as ProSuggest} from "./pro-suggest.svg";
export {default as BuilderCartFill} from "./builder-cart-filled.svg";
export {default as BuilderCart} from "./builder-cart.svg";
export {default as ThreeDotsFill} from "./3-dot-fill.svg";
export {default as Password02} from "./password-02.svg";
export {default as Fire} from "./fire.svg";
export {default as Lighting} from "./lighting.svg";
export {default as NVBLogoBlackWhite} from "./nvb-logo-black-white.svg";
export {default as TicketFill} from "./ticket-fill.svg";
export {default as BookmarkFill} from "./bookmark-fill.svg";
export {default as ConnectFill} from "./connector-fill.svg";
export {default as UserFill} from "./user-fill.svg";
export {default as ShirtFill} from "./shirt-fill.svg";
export {default as HeadphoneFill} from "./headphone-fill.svg";
export {default as MessageFill} from "./message-fill.svg";
export {default as NVBPlayWhite} from "./nvb-white.svg";
export {default as FbBlack} from "./fb-black.svg";
export {default as TiktokBlack} from "./tiktok-black.svg";
export {default as ShoppeBlack} from "./shoppe-black.svg";
export {default as YellowCrown} from "./crown.svg";

// SOCIALS
export {default as FacebookIcon} from "./socials/facebook.svg";
export {default as MessengerIcon} from "./socials/messenger.svg";
export {default as ZaloIcon} from "./socials/zalo.svg";
export {default as TelegramIcon} from "./socials/telegram.svg";
export {default as TwitterIcon} from "./socials/x_dark.svg";

// CHATS APP
export { default as BotChatIcon } from "./chats/nvbplay-bot.svg";
export { default as StarIcon } from "./chats/star.svg";
export { default as StarLinearIcon } from "./chats/star-linear.svg";
export { default as ArrowPopupIcon } from "./chats/arrow-popup.svg";
export { default as NVBPlayAvt } from "./chats/nvbplay-avt.svg";
export { default as ShopIcon } from "./chats/shop.svg";
export { default as ProductIcon } from "./chats/product.svg";
export { default as NVBLogoIcon } from "./chats/nvb-logo.svg";
export { default as DiscountIcon } from "./chats/discount.svg";
export { default as RefundIcon } from "./chats/refund.svg";
