// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banners: dynamic(() => import("./Banners")),
  categories: dynamic(() => import("./Categories")),
  collections: dynamic(() => import("./Collections")),
  deals: dynamic(() => import("./Deals")),
  events: dynamic(() => import("./Events")),
  example: dynamic(() => import("./Example")),
  forms: dynamic(() => import("./Forms")),
  grid_sections: dynamic(() => import("./GridSections")),
  livestreams: dynamic(() => import("./Livestreams")),
  memberships: dynamic(() => import("./Memberships")),
  news: dynamic(() => import("./News")),
  offers: dynamic(() => import("./Offers")),
  products: dynamic(() => import("./Products")),
  promotions: dynamic(() => import("./Promotions")),
  suggestions: dynamic(() => import("./Suggestions")),
};
